name: docker-image-push-admin

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build: 
    if: ${{ !contains(github.event.head_commit.author.name, 'Github Actions bot to update .env with latest tags') }} 
    uses: e-mission/e-mission-server/.github/workflows/reusable_image_build_push.yml@master
    with:
      repo: ${{ github.event.repository.name }}
      branch: ${{ github.ref_name }}
    secrets: inherit
