name: docker-image-push-admin

on:
  push:
    branches: [ master, cleanup-cicd ]

  workflow_dispatch:

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Fetch server image tag
      id: get-server-tag
      run: |
        response=$(curl -s \
          -H "Authorization: Bearer ${{ secrets.GH_FG_PAT_TAGS }}" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/MukuFlash03/e-mission-server/contents/.env.tags?ref=cleanup-cicd)
        
        content=$(echo "$response" | jq -r .content)
        decoded_content=$(echo "$content" | base64 --decode)
        SERVER_IMAGE_TAG=$(echo "$decoded_content" | grep "SERVER_IMAGE_TAG=" | cut -d'=' -f2)
        echo "SERVER_IMAGE_TAG=$SERVER_IMAGE_TAG" >> "$GITHUB_OUTPUT"

    - name: Set docker image tags
      id: set-tags
      run: |
        set -a; source .env.tags; set +a
        echo "ADMIN_DASH_IMAGE_TAG=${ADMIN_DASH_IMAGE_TAG}" >> "$GITHUB_OUTPUT"

    - name: Print input docker image tags
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Current admin-dash image tag (push): ${{ steps.set-tags.outputs.ADMIN_DASH_IMAGE_TAG }}"
        echo "Latest server image tag (${{ github.event_name }}): ${{ steps.get-server-tag.outputs.SERVER_IMAGE_TAG }}"

    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Get current date # get the date of the build
      id: date
      run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_OUTPUT"

    - name: Run a one-line script
      run: echo running in repo ${GITHUB_REPOSITORY#*/} branch ${GITHUB_REF##*/} on ${{ steps.date.outputs.date }}

    - name: build docker image
      run: |
        SERVER_IMAGE_TAG=${{ steps.get-server-tag.outputs.SERVER_IMAGE_TAG }} docker compose -f docker-compose-prod.yml build
        docker images

    - name: rename docker image
      run: |
        docker image tag e-mission/opdash:0.0.1 $DOCKER_USER/${GITHUB_REPOSITORY#*/}:${GITHUB_REF##*/}_${{ steps.date.outputs.date }}

    - name: push docker image
      run: |
        docker push $DOCKER_USER/${GITHUB_REPOSITORY#*/}:${GITHUB_REF##*/}_${{ steps.date.outputs.date }}

    - name: Update .env.tags file 
      run: |
        echo "ADMIN_DASH_IMAGE_TAG=${{ steps.date.outputs.date }}" > .env.tags

    - name: Add, Commit, Push changes to .env.tags file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Actions bot to update .env.tags with latest tags"
        if git diff --quiet; then
          echo "Latest timestamp already present in .env.tags file, no changes to commit"
        else
          git add .env.tags
          git commit -m "Updated docker image tags in .env.tags file to the latest timestamp"
          git push origin 
        fi

    - name: Create artifact text file
      run: |
        echo ${{ steps.date.outputs.date }} > admin_dash_tag_file.txt
        echo "Created tag text file"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: admin-dash-image-tag
          path: admin_dash_tag_file.txt
          overwrite: true

