name: docker-image-push-admin

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

  debug-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print commit info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "Ref type: ${{ github.ref_type }}"
          echo "Default branch: ${{ github.event.repository.default_branch }}"

  get-branch-name:
    runs-on: ubuntu-latest
    
    outputs:
      branch_name: ${{ steps.get-branch-name.outputs.branch_name }}

    steps:
      - name: Get branch name based on ref_type
        id: get-branch-name
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            target_branch=${{ github.event.release.target_commitish }}
            echo "branch_name=${target_branch}" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref_type }}" == "branch" ]; then
            echo "branch_name=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"    
          fi

  build: 
    if: ${{ !contains(github.event.release.body, 'Triggered on e-mission-server new release. Bumping up release version.') }}
    needs: [get-branch-name]
    uses: MukuFlash03/e-mission-server/.github/workflows/reusable_image_build_push.yml@cleanup-cicd
    with:
      repo: ${{ github.event.repository.name }}
      branch: ${{ needs.get-branch-name.outputs.branch_name }}
    secrets: inherit
