name: docker-image-push-admin

on:
  push:
    branches: [ master, cleanup-cicd ]
 
jobs:
  build:  
    uses: MukuFlash03/e-mission-server/.github/workflows/reusable_image_build_push.yml@cleanup-cicd
    with:
      repo: ${GITHUB_REPOSITORY#*/}
      branch: ${GITHUB_REF##*/}
    secrets: inherit
  